### ISSUE TITLE
http status code 400 on validation failure

### ISSUE THREAD

**Issue by mitjap** [petreboy14/express-joi#13]
I'd recommend you send error 400 on validation failure. I dont see a reason why validation error would be server error and not user error

From http://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html

    10.4.1 400 Bad Request
    The request could not be understood by the server due to malformed syntax. The client SHOULD NOT repeat the request without modifications.

    10.5.1 500 Internal Server Error
    The server encountered an unexpected condition which prevented it from fulfilling the request.

**Comment by petreboy14** [comment]
Should be fixed now. Bumped to version 0.3.1

**Comment by parkan** [comment]
Why did you hardcode 400 here? The previous behavior (calling `next(error)`) is the correct method of emitting errors in express, which can then be handled in error middleware as appropriate. You are also throwing away `err.details`, which is needed to dispatch on the error correctly (by code/prefix)

@mitjap: you were seeing 500s because you did not register an error middleware to handle `ValidationError` so the error propagated to the default handler, which defaults to 500. You should add something like

```
function joiErrorHandler(err, req, res, next) {
  if (e && e.error && e.name === 'ValidationError') {
    res.status(400);
    res.end(JSON.stringify({ message: formatMessage(err.details) }));
  } else {
    next(err);
  }
}
// ... routes
app.use(joiErrorHandler);
```

and revert this commit.

**Comment by parkan** [comment]
Addressed in https://github.com/petreboy14/express-joi/pull/14
